### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by shkr** [Openfuel/openfuel#28] opened 2019-12-27 07:22 UTC
**Describe the bug**
(node:11690) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]

**To Reproduce**
1. git clone git@github.com:Openfuel/openfuel.git
2. npm install
3. npm start

**Expected behavior**
> openfuel@4.0.0 start /home/shkr/Documents/repos/openfuel
> node ./bin/www

Developer key: bryE6tKlkBUdPfU3sF2sB7Nuxp1t4eiGEI6hk90R
Verify your account in /me with this key
(node:11690) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

openfuel is listening on http://localhost:8080

this link should work

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Additional context**
Complete error log
```
$ npm start

> openfuel@4.0.0 start /home/shkr/Documents/repos/openfuel
> node ./bin/www

Developer key: bryE6tKlkBUdPfU3sF2sB7Nuxp1t4eiGEI6hk90R
Verify your account in /me with this key
(node:11690) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

openfuel is listening on http://localhost:8080

(node:11690) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/home/shkr/Documents/repos/openfuel/node_modules/mongodb/lib/core/topologies/server.js:433:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at createConnection (/home/shkr/Documents/repos/openfuel/node_modules/mongodb/lib/core/connection/pool.js:577:14)
    at connect (/home/shkr/Documents/repos/openfuel/node_modules/mongodb/lib/core/connection/pool.js:1007:11)
    at makeConnection (/home/shkr/Documents/repos/openfuel/node_modules/mongodb/lib/core/connection/connect.js:31:7)
    at callback (/home/shkr/Documents/repos/openfuel/node_modules/mongodb/lib/core/connection/connect.js:247:5)
    at Socket.err (/home/shkr/Documents/repos/openfuel/node_modules/mongodb/lib/core/connection/connect.js:276:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:11690) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11690) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11690) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/home/shkr/Documents/repos/openfuel/node_modules/mongodb/lib/core/topologies/server.js:433:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at createConnection (/home/shkr/Documents/repos/openfuel/node_modules/mongodb/lib/core/connection/pool.js:577:14)
    at connect (/home/shkr/Documents/repos/openfuel/node_modules/mongodb/lib/core/connection/pool.js:1007:11)
    at makeConnection (/home/shkr/Documents/repos/openfuel/node_modules/mongodb/lib/core/connection/connect.js:31:7)
    at callback (/home/shkr/Documents/repos/openfuel/node_modules/mongodb/lib/core/connection/connect.js:247:5)
    at Socket.err (/home/shkr/Documents/repos/openfuel/node_modules/mongodb/lib/core/connection/connect.js:276:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:11690) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

/home/shkr/Documents/repos/openfuel/node_modules/mubsub/node_modules/mongodb/lib/mongo_client.js:421
          throw err
          ^
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/home/shkr/Documents/repos/openfuel/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/home/shkr/Documents/repos/openfuel/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/home/shkr/Documents/repos/openfuel/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

npm ERR! Linux 5.0.0-37-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! openfuel@4.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openfuel@4.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the openfuel package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs openfuel
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls openfuel
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/shkr/Documents/repos/openfuel/npm-debug.log
```

**Comment by shkr** [comment] 2019-12-27 07:24
@yashsaxena i have assigned you just to loop you in. Please bring into the discussion who ever can help me with this issue.

**Comment by littledivy** [comment] 2019-12-27 13:27
@shkr Make sure if you have the mongodb server running at localhost:27017

**Comment by shkr** [comment] 2019-12-27 20:17
Okay. Can you share the code you use to install and run mongodb on localhost:27017?

**Comment by dan-online** [comment] 2019-12-28 07:52
@shkr https://docs.mongodb.com/manual/administration/install-community/ and then using mongod to start

**Comment by littledivy** [comment] 2020-03-12 03:15
@shkr I hope the issue is resolved... Closing the issue

**Closed as completed by littledivy** 2020-03-12 03:15 UTC
